/*
===========================================================================

Builder

Copyright (c) 2025 Dan Moody

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===========================================================================
*/

#include "builder_local.h"

#include "core/include/string_builder.h"
#include "core/include/file.h"
#include "core/include/paths.h"
#include "core/include/string_helpers.h"
#include "core/include/debug.h"

bool8 GenerateVSCodeJSONFiles( buildContext_t *context, BuilderOptions *options ) {
	const char *dotVSCodeFolder = tprintf( "%s%c.vscode", context->inputFilePath.data, PATH_SEPARATOR );

	if ( !folder_create_if_it_doesnt_exist( dotVSCodeFolder ) ) {
		error( "Failed to create .vscode folder at \"%s\".\n", context->inputFilePath.data );
		return false;
	}

	const char *builderPath = options->vsCodeJSONOptions.builderPath.empty() ? BUILDER_PROGRAM_NAME : options->vsCodeJSONOptions.builderPath.c_str();

	// c_cpp_properties.json
	{
		if ( options->vsCodeJSONOptions.cppPropertiesConfigs.empty() ) {
			LogVerbose( "VS Code JSON generation was requested, but no c_cpp_properties JSON data was found.  All found BuildConfigs will be used as defaults.\n" );

			options->vsCodeJSONOptions.cppPropertiesConfigs.reserve( options->configs.size() );

			For ( u32, configIndex, 0, options->configs.size() ) {
				options->vsCodeJSONOptions.cppPropertiesConfigs.push_back( {
					.config = options->configs[configIndex],
				} );
			}
		}

		const char *cppPropertiesJSONFilename = tprintf( "%s%cc_cpp_properties.json", dotVSCodeFolder, PATH_SEPARATOR );

		printf( "Generating %s ... ", cppPropertiesJSONFilename );

		StringBuilder cppPropertiesJSONContent = {};
		defer( string_builder_destroy( &cppPropertiesJSONContent ) );

		string_builder_reset( &cppPropertiesJSONContent );

		string_builder_appendf( &cppPropertiesJSONContent, "// This file was auto-generated by Builder.\n" );
		string_builder_appendf( &cppPropertiesJSONContent, "{\n" );
		string_builder_appendf( &cppPropertiesJSONContent, "\t\"configurations\": [\n" );

		For ( u64, configIndex, 0, options->vsCodeJSONOptions.cppPropertiesConfigs.size() ) {
			VSCodeCppPropertiesConfig *cppPropertiesConfig = &options->vsCodeJSONOptions.cppPropertiesConfigs[configIndex];

			BuildConfig *config = &cppPropertiesConfig->config;

			const char *configName = cppPropertiesConfig->name.empty() ? config->name.c_str() : cppPropertiesConfig->name.c_str();

			string_builder_appendf( &cppPropertiesJSONContent, "\t\t{\n" );
			string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\"name\": \"%s\",\n", configName );

			if ( !config->additionalIncludes.empty() ) {
				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\"includePath\": [\n" );
				For ( u32, includeIndex, 0, config->additionalIncludes.size() ) {
					string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\t\"%s\",\n", config->additionalIncludes[includeIndex].c_str() );
				}
				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t],\n" );
			}

			if ( !config->defines.empty() ) {
				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\"defines\": [\n" );
				For ( u32, defineIndex, 0, config->defines.size() ) {
					string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\t\"%s\",\n", config->defines[defineIndex].c_str() );
				}
				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t],\n" );
			}

			if ( !options->compilerPath.empty() ) {
				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\"compilerPath\": \"%s\",\n", options->compilerPath.c_str() );
			}

			if ( config->languageVersion != LANGUAGE_VERSION_UNSET ) {
				const char *standardKey = NULL;
				switch ( config->languageVersion ) {
					case LANGUAGE_VERSION_C89:
					case LANGUAGE_VERSION_C99:
					case LANGUAGE_VERSION_C11:
					case LANGUAGE_VERSION_C17:
					case LANGUAGE_VERSION_C23:
						standardKey = "cStandard";
						break;

					case LANGUAGE_VERSION_CPP11:
					case LANGUAGE_VERSION_CPP14:
					case LANGUAGE_VERSION_CPP17:
					case LANGUAGE_VERSION_CPP20:
					case LANGUAGE_VERSION_CPP23:
						standardKey = "cppStandard";
						break;

					case LANGUAGE_VERSION_UNSET:
						break;
				}

				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\"%s\": \"%s\",\n", standardKey, LanguageVersionToString( config->languageVersion ) );
			}

			if ( cppPropertiesConfig->intelliSenseMode != VSCODE_INTELLISENSE_MODE_UNSET ) {
				const char *intelliSenseModeString = NULL;
				switch ( cppPropertiesConfig->intelliSenseMode ) {
					case VSCODE_INTELLISENSE_MODE_LINUX_CLANG_X64:		intelliSenseModeString = "linux-clang-x64";		break;
					case VSCODE_INTELLISENSE_MODE_LINUX_CLANG_X86:		intelliSenseModeString = "linux-clang-x86";		break;
					case VSCODE_INTELLISENSE_MODE_LINUX_CLANG_ARM64:	intelliSenseModeString = "linux-clang-arm64";	break;
					case VSCODE_INTELLISENSE_MODE_LINUX_CLANG_ARM:		intelliSenseModeString = "linux-clang-arm";		break;
					case VSCODE_INTELLISENSE_MODE_LINUX_GCC_X64:		intelliSenseModeString = "linux-gcc-x64";		break;
					case VSCODE_INTELLISENSE_MODE_LINUX_GCC_X86:		intelliSenseModeString = "linux-gcc-x86";		break;
					case VSCODE_INTELLISENSE_MODE_LINUX_GCC_ARM64:		intelliSenseModeString = "linux-gcc-arm64";		break;
					case VSCODE_INTELLISENSE_MODE_LINUX_GCC_ARM:		intelliSenseModeString = "linux-gcc-arm";		break;
					case VSCODE_INTELLISENSE_MODE_WINDOWS_MSVC_X64:		intelliSenseModeString = "windows-msvc-x64";	break;
					case VSCODE_INTELLISENSE_MODE_WINDOWS_MSVC_X86:		intelliSenseModeString = "windows-msvc-x86";	break;
					case VSCODE_INTELLISENSE_MODE_WINDOWS_MSVC_ARM64:	intelliSenseModeString = "windows-msvc-arm64";	break;
					case VSCODE_INTELLISENSE_MODE_WINDOWS_MSVC_ARM:		intelliSenseModeString = "windows-msvc-arm";	break;
					case VSCODE_INTELLISENSE_MODE_WINDOWS_CLANG_X64:	intelliSenseModeString = "windows-clang-x64";	break;
					case VSCODE_INTELLISENSE_MODE_WINDOWS_CLANG_X86:	intelliSenseModeString = "windows-clang-x86";	break;
					case VSCODE_INTELLISENSE_MODE_UNSET:
						break;
				}

				string_builder_appendf( &cppPropertiesJSONContent, "\t\t\t\"intelliSenseMode\": \"%s\",\n", intelliSenseModeString );
			}

			string_builder_appendf( &cppPropertiesJSONContent, "\t\t},\n" );
		}

		string_builder_appendf( &cppPropertiesJSONContent, "\t],\n" );
		string_builder_appendf( &cppPropertiesJSONContent, "\t\"version\": 4\n" );
		string_builder_appendf( &cppPropertiesJSONContent, "}\n" );

		if ( !WriteStringBuilderToFile( &cppPropertiesJSONContent, cppPropertiesJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", cppPropertiesJSONFilename );
			return false;
		}

		printf( "Done\n" );
	}

	// tasks.json
	{
		if ( options->vsCodeJSONOptions.taskConfigs.empty() ) {
			LogVerbose( "VS Code JSON generation was requested, but no tasks JSON data was found.  All found BuildConfigs will be used as defaults.\n" );

			options->vsCodeJSONOptions.taskConfigs.reserve( options->configs.size() );

			For ( u32, configIndex, 0, options->configs.size() ) {
				options->vsCodeJSONOptions.taskConfigs.push_back( {
					options->configs[configIndex]
				} );
			}
		}

		const char *tasksJSONFilename = tprintf( "%s%ctasks.json", dotVSCodeFolder, PATH_SEPARATOR );

		printf( "Generating %s ... ", tasksJSONFilename );

		StringBuilder tasksJSONContent = {};
		defer( string_builder_destroy( &tasksJSONContent ) );

		string_builder_reset( &tasksJSONContent );

		string_builder_appendf( &tasksJSONContent, "{\n" );
		string_builder_appendf( &tasksJSONContent, "\t// See https://go.microsoft.com/fwlink/?LinkId=733558\n" );
		string_builder_appendf( &tasksJSONContent, "\t// for the documentation about the tasks.json format\n" );
		string_builder_appendf( &tasksJSONContent, "\t// This file was auto-generated by Builder.\n" );
		string_builder_appendf( &tasksJSONContent, "\t\"version\": \"2.0.0\",\n" );	// TODO(DM): 17/04/2026: do we need to expose the version to VSCodeJSONOptions?
		string_builder_appendf( &tasksJSONContent, "\t\"tasks\": [\n" );
		For ( u64, configIndex, 0, options->vsCodeJSONOptions.taskConfigs.size() ) {
			VSCodeTaskConfig *taskConfig = &options->vsCodeJSONOptions.taskConfigs[configIndex];

			BuildConfig *config = &taskConfig->config;

			string_builder_appendf( &tasksJSONContent, "\t\t{\n" );
			string_builder_appendf( &tasksJSONContent, "\t\t\t\"label\": \"Build %s\",\n", taskConfig->config.name.c_str() );
			string_builder_appendf( &tasksJSONContent, "\t\t\t\"type\": \"shell\",\n" );
			string_builder_appendf( &tasksJSONContent, "\t\t\t\"command\": \"%s\",\n", builderPath );
			string_builder_appendf( &tasksJSONContent, "\t\t\t\"args\": [\n" );
			{
				string_builder_appendf( &tasksJSONContent, "\t\t\t\t\"%s\",\n", context->inputFile );
				string_builder_appendf( &tasksJSONContent, "\t\t\t\t\"%s%s\"", ARG_CONFIG, config->name.c_str() );

				if ( taskConfig->additionalBuildArgs.size() ) {
					string_builder_appendf( &tasksJSONContent, ",\n" );

					For ( u32, argIndex, 0, taskConfig->additionalBuildArgs.size() ) {
						string_builder_appendf( &tasksJSONContent, "\t\t\t\t\"%s\"", taskConfig->additionalBuildArgs[argIndex].c_str() );

						if ( argIndex < taskConfig->additionalBuildArgs.size() - 1 ) {
							string_builder_appendf( &tasksJSONContent, ",\n" );
						} else {
							string_builder_appendf( &tasksJSONContent, "\n" );
						}
					}
				} else {
					string_builder_appendf( &tasksJSONContent, "\n" );
				}
			}
			string_builder_appendf( &tasksJSONContent, "\t\t\t],\n" );
			string_builder_appendf( &tasksJSONContent, "\t\t},\n" );
		}
		string_builder_appendf( &tasksJSONContent, "\t]\n" );
		string_builder_appendf( &tasksJSONContent, "}\n" );

		if ( !WriteStringBuilderToFile( &tasksJSONContent, tasksJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", tasksJSONFilename );
			return false;
		}

		printf( "Done\n" );
	}

	// launch.json
	{
		if ( options->vsCodeJSONOptions.launchConfigs.empty() ) {
			LogVerbose( "VS Code JSON generation was requested, but no launch JSON data was found.  All found BuildConfigs will be used as defaults.\n" );

			options->vsCodeJSONOptions.launchConfigs.reserve( options->configs.size() );

			For ( u32, configIndex, 0, options->configs.size() ) {
				const BuildConfig *config = &options->configs[configIndex];

				VSCodeLaunchConfig launchConfig = {
					.binaryName = tprintf( "${workspaceFolder}/%s", BuildConfig_GetFullBinaryName( config ) ),
					.cwd = "${workspaceFolder}",
				};

#if defined( _WIN64 )
				launchConfig.debuggerType = VSCODE_DEBUGGER_TYPE_CPPVSDBG;
#elif defined( __linux__ )
				launchConfig.linuxDebugger = {
					.miMode = "gdb",
					.miDebuggerPath = "/usr/bin/gdb",
				};
#endif

				options->vsCodeJSONOptions.launchConfigs.push_back( launchConfig );
			}
		}

		const char *launchJSONFilename = tprintf( "%s%claunch.json", dotVSCodeFolder, PATH_SEPARATOR );

		printf( "Generating %s ... ", launchJSONFilename );

		StringBuilder launchJSONContent = {};
		defer( string_builder_destroy( &launchJSONContent ) );

		string_builder_reset( &launchJSONContent );

		string_builder_appendf( &launchJSONContent, "{\n" );
		string_builder_appendf( &launchJSONContent, "\t// Use IntelliSense to learn about possible attributes.\n" );
		string_builder_appendf( &launchJSONContent, "\t// Hover to view descriptions of existing attributes.\n" );
		string_builder_appendf( &launchJSONContent, "\t// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387\n" );
		string_builder_appendf( &launchJSONContent, "\t// This file was auto-generated by Builder.\n" );
		string_builder_appendf( &launchJSONContent, "\t\"version\": \"0.2.0\",\n" );	// TODO(DM): 17/04/2026: do we need to expose the version to VSCodeJSONOptions?
		string_builder_appendf( &launchJSONContent, "\t\"configurations\": [\n" );

		For ( u32, configIndex, 0, options->vsCodeJSONOptions.launchConfigs.size() ) {
			VSCodeLaunchConfig *launchConfig = &options->vsCodeJSONOptions.launchConfigs[configIndex];

			string_builder_appendf( &launchJSONContent,          "\t\t{\n" );
			string_builder_appendf( &launchJSONContent, tprintf( "\t\t\t\"name\": \"%s\",\n", launchConfig->binaryName.c_str() ) );
			{
				VSCodeDebuggerType debuggerType = ( launchConfig->debuggerType == VSCODE_DEBUGGER_TYPE_UNSET ) ? VSCODE_DEBUGGER_TYPE_CPPDBG_GDB : launchConfig->debuggerType;

				bool8 hasPlatformConfigs = !launchConfig->linuxDebugger.miMode.empty() || !launchConfig->windowsDebugger.miMode.empty();

				switch ( debuggerType ) {
					case VSCODE_DEBUGGER_TYPE_CPPDBG_GDB:
						string_builder_appendf( &launchJSONContent, "\t\t\t\"type\": \"cppdbg\",\n" );
						if ( !hasPlatformConfigs ) {
							string_builder_appendf( &launchJSONContent, "\t\t\t\"MIMode\": \"gdb\",\n" );
						}
						break;

					case VSCODE_DEBUGGER_TYPE_CPPDBG_LLDB:
						string_builder_appendf( &launchJSONContent, "\t\t\t\"type\": \"cppdbg\",\n" );
						if ( !hasPlatformConfigs ) {
							string_builder_appendf( &launchJSONContent, "\t\t\t\"MIMode\": \"lldb\",\n" );
						}
						break;

					case VSCODE_DEBUGGER_TYPE_CPPVSDBG:
						string_builder_appendf( &launchJSONContent, "\t\t\t\"type\": \"cppvsdbg\",\n" );
						break;

					case VSCODE_DEBUGGER_TYPE_UNSET:
						break;
				}
			}

			string_builder_appendf( &launchJSONContent, "\t\t\t\"request\": \"launch\",\n" );
			string_builder_appendf( &launchJSONContent, "\t\t\t\"program\": \"%s\",\n", launchConfig->binaryName.c_str() );

			if ( !launchConfig->args.empty() ) {
				string_builder_appendf( &launchJSONContent, "\t\t\t\"args\": [\n" );

				For ( u32, argIndex, 0, launchConfig->args.size() ) {
					string_builder_appendf( &launchJSONContent, "\t\t\t\t\"%s\"", launchConfig->args[argIndex].c_str() );

					if ( argIndex < launchConfig->args.size() - 1 ) {
						string_builder_appendf( &launchJSONContent, ",\n" );
					} else {
						string_builder_appendf( &launchJSONContent, "\n" );
					}
				}

				string_builder_appendf( &launchJSONContent, "\t\t\t],\n" );
			}

			{
				const char *cwd = launchConfig->cwd.empty() ? "${workspaceFolder}" : launchConfig->cwd.c_str();
				string_builder_appendf( &launchJSONContent, "\t\t\t\"cwd\": \"%s\",\n", cwd );	// TODO(DM): 16/04/2026: do we want to expose this to VSCodeJSONOptions?
			}

			if ( !launchConfig->linuxDebugger.miMode.empty() ) {
				string_builder_appendf( &launchJSONContent, "\t\t\t\"linux\": {\n" );
				string_builder_appendf( &launchJSONContent, "\t\t\t\t\"MIMode\": \"%s\",\n", launchConfig->linuxDebugger.miMode.c_str() );
				if ( !launchConfig->linuxDebugger.miDebuggerPath.empty() ) {
					string_builder_appendf( &launchJSONContent, "\t\t\t\t\"miDebuggerPath\": \"%s\",\n", launchConfig->linuxDebugger.miDebuggerPath.c_str() );
				}
				string_builder_appendf( &launchJSONContent, "\t\t\t},\n" );
			}

			if ( !launchConfig->windowsDebugger.miMode.empty() ) {
				string_builder_appendf( &launchJSONContent, "\t\t\t\"windows\": {\n" );
				string_builder_appendf( &launchJSONContent, "\t\t\t\t\"MIMode\": \"%s\",\n", launchConfig->windowsDebugger.miMode.c_str() );
				if ( !launchConfig->windowsDebugger.miDebuggerPath.empty() ) {
					string_builder_appendf( &launchJSONContent, "\t\t\t\t\"miDebuggerPath\": \"%s\",\n", launchConfig->windowsDebugger.miDebuggerPath.c_str() );
				}
				string_builder_appendf( &launchJSONContent, "\t\t\t},\n" );
			}

			if ( !launchConfig->setupCommands.empty() ) {
				string_builder_appendf( &launchJSONContent, "\t\t\t\"setupCommands\": [\n" );

				For ( u32, cmdIndex, 0, launchConfig->setupCommands.size() ) {
					const VSCodeSetupCommand *cmd = &launchConfig->setupCommands[cmdIndex];
					string_builder_appendf( &launchJSONContent, "\t\t\t\t{\n" );
					string_builder_appendf( &launchJSONContent, "\t\t\t\t\t\"description\": \"%s\",\n", cmd->description.c_str() );
					string_builder_appendf( &launchJSONContent, "\t\t\t\t\t\"text\": \"%s\",\n", cmd->text.c_str() );
					string_builder_appendf( &launchJSONContent, "\t\t\t\t\t\"ignoreFailures\": %s,\n", cmd->ignoreFailures ? "true" : "false" );
					string_builder_appendf( &launchJSONContent, "\t\t\t\t},\n" );
				}

				string_builder_appendf( &launchJSONContent, "\t\t\t],\n" );
			}

			string_builder_appendf( &launchJSONContent, "\t\t},\n" );
		}

		string_builder_appendf( &launchJSONContent, "\t]\n" );
		string_builder_appendf( &launchJSONContent, "}\n" );

		if ( !WriteStringBuilderToFile( &launchJSONContent, launchJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", launchJSONFilename );
			return false;
		}

		printf( "Done\n" );
	}

	printf( "\n" );

	return true;
}