/*
===========================================================================

Builder

Copyright (c) 2025 Dan Moody

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===========================================================================
*/

#include "builder_local.h"

#include "core/include/paths.h"
#include "core/include/string_helpers.h"
#include "core/include/file.h"
#include "core/include/debug.h"
#include "core/include/string_builder.h"

bool8 GenerateZedJSONFiles( buildContext_t *context, BuilderOptions *options ) {
	const char *dotZedFolder = tprintf( "%s%c.zed", context->inputFilePath.data, PATH_SEPARATOR );

	if ( !folder_create_if_it_doesnt_exist( dotZedFolder ) ) {
		error( "Failed to create .zed folder at \"%s\".\n", context->inputFilePath.data );
		return false;
	}

	const char *builderPath = options->zedJSONOptions.builderPath.empty() ? BUILDER_PROGRAM_NAME : options->zedJSONOptions.builderPath.c_str();

	// tasks.json
	{
		if ( options->zedJSONOptions.taskConfigs.empty() ) {
			LogVerbose( "Zed JSON generation was requested, but no tasks JSON data was found.  All found BuildConfigs will be used as defaults.\n" );

			options->zedJSONOptions.taskConfigs.reserve( options->configs.size() );

			For ( u32, configIndex, 0, options->configs.size() ) {
				options->zedJSONOptions.taskConfigs.push_back( {
					options->configs[configIndex]
				} );
			}
		}

		const char *tasksJSONFilename = tprintf( "%s%ctasks.json", dotZedFolder, PATH_SEPARATOR );

		printf( "Generating %s ... ", tasksJSONFilename );

		StringBuilder tasksJSONContent = {};
		defer( string_builder_destroy( &tasksJSONContent ) );

		string_builder_reset( &tasksJSONContent );

		string_builder_appendf( &tasksJSONContent, "// Project tasks configuration. See https://zed.dev/docs/tasks for documentation.\n" );
		string_builder_appendf( &tasksJSONContent, "// This file was auto-generated by Builder.\n" );
		string_builder_appendf( &tasksJSONContent, "[\n" );
		For ( u32, configIndex, 0, options->zedJSONOptions.taskConfigs.size() ) {
			ZedTaskConfig *taskConfig = &options->zedJSONOptions.taskConfigs[configIndex];

			string_builder_appendf( &tasksJSONContent, "\t{\n" );
			string_builder_appendf( &tasksJSONContent, "\t\t\"label\": \"Build %s\",\n", taskConfig->config.name.c_str() );
			string_builder_appendf( &tasksJSONContent, "\t\t\"command\": \"%s\",\n", builderPath );
			string_builder_appendf( &tasksJSONContent, "\t\t\"args\": [\n" );
			{
				string_builder_appendf( &tasksJSONContent, "\t\t\t\"%s\",\n", context->inputFile );
				string_builder_appendf( &tasksJSONContent, "\t\t\t\"%s%s\"", ARG_CONFIG, taskConfig->config.name.c_str() );

				if ( taskConfig->args.size() ) {
					string_builder_appendf( &tasksJSONContent, ",\n" );

					For ( u32, argIndex, 0, taskConfig->args.size() ) {
						string_builder_appendf( &tasksJSONContent, "\t\t\t\"%s\"", taskConfig->args[argIndex].c_str() );

						if ( argIndex < taskConfig->args.size() - 1 ) {
							string_builder_appendf( &tasksJSONContent, ",\n" );
						} else {
							string_builder_appendf( &tasksJSONContent, "\n" );
						}
					}
				} else {
					string_builder_appendf( &tasksJSONContent, "\n" );
				}
			}
			string_builder_appendf( &tasksJSONContent, "\t\t]\n" );

			if ( configIndex < options->zedJSONOptions.taskConfigs.size() - 1 ) {
				string_builder_appendf( &tasksJSONContent, "\t},\n" );
			} else {
				string_builder_appendf( &tasksJSONContent, "\t}\n" );
			}
		}
		string_builder_appendf( &tasksJSONContent, "]\n" );

		if ( !WriteStringBuilderToFile( &tasksJSONContent, tasksJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", tasksJSONFilename );
			return false;
		}

		printf( "Done\n" );
	}

	// debug.json
	{
		if ( options->zedJSONOptions.debugConfigs.empty() ) {
			LogVerbose( "Zed JSON generation was requested, but no debug JSON data was found.  All found BuildConfigs will be used as defaults.\n" );

			options->zedJSONOptions.debugConfigs.reserve( options->configs.size() );

			For ( u32, configIndex, 0, options->configs.size() ) {
				const BuildConfig *config = &options->configs[configIndex];

				const char *zedDebugConfigBinaryName = string_replace( BuildConfig_GetFullBinaryName( config ), '\\', '/' );

				ZedDebugConfig debugConfig = {
					.label		= tprintf( "Debug %s", config->name.c_str() ),
					.binaryName	= tprintf( "${ZED_WORKTREE_ROOT}/%s", zedDebugConfigBinaryName ),
					.cwd		= "${ZED_WORKTREE_ROOT}",
					.adapter	= ZED_DEBUGGER_ADAPTER_CODELLDB,
					.request	= ZED_DEBUGGER_REQUEST_LAUNCH,
				};

				options->zedJSONOptions.debugConfigs.push_back( debugConfig );
			}
		}

		const char *debugJSONFilename = tprintf( "%s%cdebug.json", dotZedFolder, PATH_SEPARATOR );

		printf( "Generating %s ... ", debugJSONFilename );

		StringBuilder debugJSONContent = {};
		defer( string_builder_destroy( &debugJSONContent ) );

		string_builder_reset( &debugJSONContent );

		string_builder_appendf( &debugJSONContent, "// Project-local debug tasks.\n" );
		string_builder_appendf( &debugJSONContent, "// For more documentation on how to configure debug tasks,\n" );
		string_builder_appendf( &debugJSONContent, "// see: https://zed.dev/docs/debugger\n" );
		string_builder_appendf( &debugJSONContent, "// This file was auto-generated by Builder.\n" );
		string_builder_appendf( &debugJSONContent, "[\n" );

		For ( u32, i, 0, options->zedJSONOptions.debugConfigs.size() ) {
			ZedDebugConfig *debugConfig = &options->zedJSONOptions.debugConfigs[i];

			if ( debugConfig->label.empty() ) {
				error( "When generating Zed debug configs (for your debug.json), the label must be set to something.  It cannot be empty.\n" );
				return false;
			}

			string_builder_appendf( &debugJSONContent, "\t{\n" );
			string_builder_appendf( &debugJSONContent, "\t\t\"label\": \"%s\",\n", debugConfig->label.c_str() );
			string_builder_appendf( &debugJSONContent, "\t\t\"program\": \"%s\",\n", debugConfig->binaryName.c_str() );

			if ( debugConfig->args.size() ) {
				string_builder_appendf( &debugJSONContent, "\t\t\"args\": [\n" );

				For ( u32, argIndex, 0, debugConfig->args.size() ) {
					string_builder_appendf( &debugJSONContent, "\t\t\t\"%s\"", debugConfig->args[argIndex].c_str() );

					if ( argIndex < debugConfig->args.size() - 1 ) {
						string_builder_appendf( &debugJSONContent, ",\n" );
					} else {
						string_builder_appendf( &debugJSONContent, "\n" );
					}
				}

				string_builder_appendf( &debugJSONContent, "\t\t],\n" );
			}

			{
				const char *cwd = debugConfig->cwd.empty() ? "${ZED_WORKTREE_ROOT}" : debugConfig->cwd.c_str();
				string_builder_appendf( &debugJSONContent, "\t\t\"cwd\": \"%s\",\n", cwd );
			}

			{
				const char *adapterStr = NULL;

				switch ( debugConfig->adapter ) {
					case ZED_DEBUGGER_ADAPTER_CODELLDB:	adapterStr = "CodeLLDB";	break;
					case ZED_DEBUGGER_ADAPTER_GDB:		adapterStr = "GDB";			break;
				}

				string_builder_appendf( &debugJSONContent, "\t\t\"adapter\": \"%s\",\n", adapterStr );
			}

			{
				const char *requestStr = NULL;

				switch ( debugConfig->request ) {
					case ZED_DEBUGGER_REQUEST_LAUNCH:	requestStr = "launch";	break;
					case ZED_DEBUGGER_REQUEST_ATTACH:	requestStr = "attach";	break;
				}

				string_builder_appendf( &debugJSONContent, "\t\t\"request\": \"%s\"\n", requestStr );
			}

			if ( i < options->zedJSONOptions.debugConfigs.size() - 1 ) {
				string_builder_appendf( &debugJSONContent, "\t},\n" );
			} else {
				string_builder_appendf( &debugJSONContent, "\t}\n" );
			}
		}

		string_builder_appendf( &debugJSONContent, "]\n" );

		if ( !WriteStringBuilderToFile( &debugJSONContent, debugJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", debugJSONFilename );
			return false;
		}

		printf( "Done\n" );
	}

	printf( "\n" );

	return true;
}
